version: '2'

services:

  node:
    container_name: NodeJS
    build:
      context: .
      dockerfile: node/Dockerfile
    volumes:
      - ./appcode:/var/www/html
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    environment:
      ENV: 'dev'
    depends_on:
      - mysql
    links:
      - "mysql:NodeMysql"

  mysql:
    image: mysql:5.7.10
    container_name: NodeMysql
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpw'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'nodemysqlpwd'
      MYSQL_DATABASE: 'retro'
    ports:
      - "3007:3306"
